language: java
sudo: required
jdk: oraclejdk8
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --depth=2147483647
  - git symbolic-ref HEAD
script: ci/travis.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
